### PR TITLE
fixed the db use command

### PR DESCRIPTION
**Pull request by rajrsingh**
change Cloudant.use to cloudant.db.use

### CODE REVIEW

**Comment by jhs** [comment]
Thanks! Can you help me understand the purpose of this pull request.

To me, it sounds like you think the documentation is unclear, perhaps that neither `Cloudant.use()` nor `cloudant.db.use()` are the preferred API? (At least, that is what I feel when thinking about your pull request.)

**Comment by rajrsingh** [comment]
Yes it's a documentation issue. I didn't see Cloudant.use() documented (although it's in the table of contents). So I thought you meant to write cloudant.db.use()

**Comment by rajrsingh** [comment]
Also, links in table of contents don't move you anywhere in the page

**Comment by jhs** [comment]
Thanks. I have written out (my understanding of) the documentation problem in #53. And I created a separate issue about the bad links in #52.

**Pull request closed without merging**
